### PR TITLE
Added ConfigureMake to ruby configs where it was missing.

### PR DESCRIPTION
**Pull request by pforai**
This should make jenkins happy

### CODE REVIEW

**Comment by rjeschmi** [comment]
there is a new ruby block as I mentioned at the top of the original PR. It needs to be merged at the same time.

**Comment by pforai** [comment]
Oh, damn! reading is hard :P

**Comment by rjeschmi** [comment]
we do need to get this merged sooner or later. I think this should be pretty easy since it includes fpm in the a dummy toolchain version, so less controversy :)

**Comment by pforai** [comment]
Totally!

**Pull request closed without merging**
